name: Feature Request
description: How can we make snoots better?
labels: [feature suggestion]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the change you would like to see.
    validations:
      required: true
