blank_issues_enabled: false
contact_links:
  - name: Support and Questions
    url: https://github.com/thislooksfun/snoots/discussions?discussions_q=category%3AQ%26A
    about: Need help or just have a general question? Please open a discussion thread.
