name: Sanity check
on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
      - name: Get abbreviated PR Commits
        id: "get-pr-commits"
        uses: thislooksfun/get-pr-commits#318748b4db0f06d9a9a2047b1e10c67624353c82
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # This only keeps the following structure for each commit:
          # { "sha": "<sha>", "commit": {"message": "<commit message>" } }
          # All other information is discarded.
          keep_keypaths: '[["sha"], ["commit", "message"]]'
      - run: >
          echo 'Commits: "${{ steps.get-pr-commits.commits }}"'
