name: Update robots.txt

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  robots:
    runs-on: ubuntu-latest
    steps:
      - name: Update robots.txt
        uses: thislooksfun/anti-ai-robots@v1
        with:
          branch: gh-pages
