name: Update robots.txt

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  robots:
    runs-on: ubuntu-latest
    steps:
      - name: Update robots.txt
        uses: ./.github/actions/template.yml
        with:
          path: docs/robots.txt
