name: Release Builder

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Changed Files
        id: collect-changed
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {sha: commit_sha, payload: {repository: {name: repo, owner: {name: owner}} }} = context;
            console.log(JSON.stringify({owner, repo, commit_sha }));
      # return github.git.getCommit({...github.})
      - name: "Confirm"
        run: "echo '${{ steps.collect-changed.outputs.result }}'"
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: username/my-repo
      #     event-type: my-event
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "commit": $COMMIT}'
