name: Publish Documentation

on:
  push:
    branches: [master]
  # TODO: Implement versioned docs.
  # BODY: The other commented sections need to be resolved at the same time as
  # BODY: this in order to implement this properly.
  # BODY: This is pending JamesIves/github-pages-deploy-action#635.
  # release:
  #   types: [published]

jobs:
  deploydoc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const fs = require("fs");
            fs.mkdirSync("docs");
            fs.writeFileSync("docs/index.md", "# Hello!\n\nThis is a simple test.");
            fs.writeFileSync("docs/about.md", "# About\n\n...why are you reading this?");
      - id: version
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            switch (context.eventName) {
              case "push":
                return "master";
              case "release":
                const pkgPth = `${process.env.GITHUB_WORKSPACE}/package.json`;
                const { version } = require(pkgPth);
                return `v${version}`;
              default:
                console.log("Something went very wrong :(");
                console.log(`Got unexpected event '${evnt}'`);
                process.exit(1);
            }
      - run: "echo new dir: '<gh-pages>/docs/${{ steps.version.outputs.result }}'"
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
          target-folder: docs/${{ steps.version.outputs.result }}
          clean: true

  # symlink:
  #   name: Update symlinks
  #   runs-on: ubuntu-latest
  #   needs: [deploydoc]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: gh-pages
  #     - uses: actions/github-script@v3
  #       with:
  #         # TODO: script to update the symlinks goes here
  #         script: ""
  #     # TODO: Commit and push the new symlinks
