name: Zip Finder

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Find Zip File
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {payload: {release: {zipball_url: zip}}} = context;
            console.log(zip);
