name: Zip Finder

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Update Zip Link
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            fs.writeFileSync("zip.url", context.payload.release.zipball_url);
      - name: Status
        run: git status
#       - name: Commit
#         run: |
#           echo "out: ${{ steps.get_zip.outputs.result }}"
