name: Zip Finder

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag
        id: get_tag
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: return context.payload.release.tag_name;

      - name: Checkout Master Branch
        uses: actions/checkout@v2.0.0
        with:
          ref: master
      - name: Update Zip URL
        uses: actions/github-script@0.3.0
        id: update_zip
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            console.log(require("process").cwd());
            const fs = require("fs");
            let pkgs = fs.readFileSync("package.json", {encoding: "utf8"});
            let pkg = JSON.parse(pkgs);
            pkg.custom_zip_url = context.payload.release.zipball_url;
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));

      - name: wtf.pt1
        run: |
          git status
          git log

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update .zip URL to version ${{ steps.get_tag.outputs.result }}" package.json

      - name: wtf.pt2
        run: |
          git status
          git log

      - name: Push Changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
